name: Release

on:
  push:
    tags: [ 'v[0-9]+\.[0-9]+\.[0-9]+']

  workflow_dispatch:

env:
  BUILD_TYPE: Release
  CPU_CORES_COUNT: 2
  CATCH2_VERSION: 'v3.4.0'

jobs:
  build-and-run-tests:
    name: Build and run tests
    uses: ./.github/workflows/build-and-run-tests.yml

  release:
    name: Release
    needs: build-and-run-tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        path: repo

    # ======================
    # Build x64 dependencies
    # ======================

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Cache x64 dependencies
      id: cache-deps-x64
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/packages-x64
        key: Release-${{ env.CATCH2_VERSION }}-amd64-dependencies

    - name: Checkout Catch2
      if: steps.cache-deps-x64.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: catchorg/Catch2
        path: deps/catch2
        ref: ${{ env.CATCH2_VERSION }}

    - name: Build and install Catch2
      if: steps.cache-deps-x64.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/deps/catch2
      run: |
        cmake -B build -S . -DBUILD_TESTING=OFF -G Ninja
        cmake --build build --config Release
        cmake --install build --prefix ${{github.workspace}}/packages-x64 --config Release

    # ======================
    # Build x86 dependencies
    # ======================

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Cache x86 dependencies
      id: cache-deps-x86
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/packages-x86
        key: Release-${{ env.CATCH2_VERSION }}-x86-dependencies

    - name: Checkout Catch2
      if: steps.cache-deps-x86.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: catchorg/Catch2
        path: deps/catch2
        ref: ${{ env.CATCH2_VERSION }}

    - if: steps.cache-deps-x86.outputs.cache-hit != 'true'
      run: |
        del /Q /S ${{github.workspace}}/deps/catch2/build/CMakeCache.txt
        del /Q /S ${{github.workspace}}/deps/catch2/build/CMakeFiles

    - name: Build and install Catch2
      if: steps.cache-deps-x86.outputs.cache-hit != 'true'
      working-directory: ${{github.workspace}}/deps/catch2
      run: |
        cmake -B build -S . -DBUILD_TESTING=OFF -G Ninja
        cmake --build build --config Release
        cmake --install build --prefix ${{github.workspace}}/packages-x86 --config Release

    - name: Build x64
      working-directory: ${{github.workspace}}/repo
      run: |
        cmake -B build -S . -G Ninja -DBUILD_TESTING=OFF -DCMAKE_PREFIX_PATH=${{github.workspace}}/packages-x64
        cmake --build build --config Release
        cmake --install build --prefix install
        rename install/bin/WinJobster.dll WinJobster-x64.dll

    - name: Delete CMake cache
      working-directory: ${{github.workspace}}/repo
      run: |
        del /Q /S build/CMakeCache.txt
        del /Q /S build/CMakeFiles

    - name: Build x86
      working-directory: ${{github.workspace}}/repo
      run: |
        cmake -B build -S . -G Ninja -DBUILD_TESTING=OFF -DCMAKE_PREFIX_PATH=${{github.workspace}}/packages-x86
        cmake --build build --config Release
        cmake --install build --prefix install
        rename install/bin/WinJobster.dll WinJobster-x86.dll

    # ==============
    # Create release
    # ==============

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: Release ${{ github.ref_name }}
        files: |
          ${{github.workspace}}/repo/install/bin/WinJobster-x64.dll
          ${{github.workspace}}/repo/install/bin/WinJobster-x86.dll
