name: Release

on:
  push:
    tags: [ 'v[0-9]+\.[0-9]+\.[0-9]+']

  workflow_dispatch:


jobs:
  build-and-run-tests:
    name: Build and run tests
    uses: ./.github/workflows/build-and-run-tests.yml

  release:
    name: Release
    needs: build-and-run-tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        path: repo

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Build x64
      working-directory: ${{github.workspace}}/repo
      run: |
        cmake -B build -S . -G Ninja -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build --prefix install
        Rename-Item -Path "install/bin/WinJobster.dll" -NewName WinJobster-x64.dll

    - name: Delete CMake cache
      working-directory: ${{github.workspace}}/repo
      run: |
        Remove-Item -LiteralPath "build/CMakeCache.txt" -Force -Recurse
        Remove-Item -LiteralPath "build/CMakeFiles" -Force -Recurse

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build x86
      working-directory: ${{github.workspace}}/repo
      run: |
        cmake -B build -S . -G Ninja -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build --prefix install
        Rename-Item -Path "install/bin/WinJobster.dll" -NewName WinJobster-x86.dll

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: Release ${{ github.ref_name }}
        files: |
          ${{github.workspace}}/repo/install/bin/WinJobster-x64.dll
          ${{github.workspace}}/repo/install/bin/WinJobster-x86.dll
